// scanner.cpp generated by reflex 5.1.0 from lexer.ll

#define REFLEX_VERSION "5.1.0"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  OPTIONS USED                                                              //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#define REFLEX_OPTION_header_file         "scanner.hpp"
#define REFLEX_OPTION_lex                 lex
#define REFLEX_OPTION_lexer               scanner
#define REFLEX_OPTION_outfile             "scanner.cpp"
#define REFLEX_OPTION_token_type          Token
#define REFLEX_OPTION_unicode             true

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %top user code                                                 //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#line 8 "lexer.ll"

#ifndef TOKEN_DEFINED
#define TOKEN_DEFINED
#include <iostream>
#include <fstream>
#include <sstream>
#include <variant>
#include <string>

class Token;

enum class token_type {
    IDENT,
    CHAR,
    UINT,
    STRING,
    OPERATOR,
    KEYWORD,
    END_OF_FILE,
};

typedef std::variant<std::string,int> token_value;

class Token {
    public:
        token_type token_t;
        token_value value;
        int line;
        int startc;
        int endc;

        Token() = delete;

        Token(token_type t, token_value&& v,int l, int sc){
            token_t = t;
            value = v;
            line = 0;
            startc = 0;
            endc =0;
        }

        Token(token_type t, token_value&& v,int l,int sc, int ec){
            token_t = t;
            value = v;
            line = l;
            startc = sc;
            endc = ec;
        }
};

#endif


////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  LEXER CLASS INCLUDE                                                       //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include "scanner.hpp"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 2: rules                                                          //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

Token scanner::lex(void)
{
  static const char *REGEX_INITIAL = "(?m)(//(?:[^\\n][\\x80-\\xbf]*)*\\n)|(#(?:[^\\n][\\x80-\\xbf]*)*\\n)|((?s:(?:\\Q/*\\E)(?:(?:.[\\x80-\\xbf]*)|\\n)*?(?:\\Q*/\\E)))|(\\n)|([\\x09\\x0d\\x20])|((?:(?:\\Q<=\\E)|(?:\\Q>=\\E)|(?:\\Q==\\E)|(?:\\Q!=\\E)|(?:\\Q&&\\E)|(?:\\Q||\\E)|(?:\\Q<<\\E)|(?:\\Q>>\\E)|(?:\\Q++\\E)|(?:\\Q--\\E)))|((?:[!%&(-/:->\\x5b\\x5d{-~]))|((?:(?:\\<int\\>|\\<void\\>|\\<extern\\>|\\<break\\>|\\<new\\>|\\<while\\>)|(?:\\<char\\>|\\<for\\>|\\<return\\>|\\<delete\\>|\\<if\\>|\\<struct\\>|\\<else\\>)))|((?:0|[1-9][0-9]*))|((?:0[Xx][0-9A-Fa-f]+))|((?:'(?:(?:[\\x00-\\x08]|[\\x0b-!]|[\\x23-&]|[(-\\x5b]|[\\x5d-\\x7f]|[\\xc2-\\xdf][\\x80-\\xbf]|\\xe0[\\xa0-\\xbf][\\x80-\\xbf]|[\\xe1-\\xec][\\x80-\\xbf][\\x80-\\xbf]|\\xed[\\x80-\\x9f][\\x80-\\xbf]|[\\xee\\xef][\\x80-\\xbf][\\x80-\\xbf]|\\xf0[\\x90-\\xbf][\\x80-\\xbf][\\x80-\\xbf]|[\\xf1-\\xf3][\\x80-\\xbf][\\x80-\\xbf][\\x80-\\xbf]|\\xf4[\\x80-\\x8f][\\x80-\\xbf][\\x80-\\xbf])|(?:\\Q \\E)|\\\\n|\\\\t|\\\\\\\\|\\\\'|\\\\\")'))|((?:\"(?:(?:[\\x00-\\x08]|[\\x0b-!]|[\\x23-&]|[(-\\x5b]|[\\x5d-\\x7f]|[\\xc2-\\xdf][\\x80-\\xbf]|\\xe0[\\xa0-\\xbf][\\x80-\\xbf]|[\\xe1-\\xec][\\x80-\\xbf][\\x80-\\xbf]|\\xed[\\x80-\\x9f][\\x80-\\xbf]|[\\xee\\xef][\\x80-\\xbf][\\x80-\\xbf]|\\xf0[\\x90-\\xbf][\\x80-\\xbf][\\x80-\\xbf]|[\\xf1-\\xf3][\\x80-\\xbf][\\x80-\\xbf][\\x80-\\xbf]|\\xf4[\\x80-\\x8f][\\x80-\\xbf][\\x80-\\xbf])|(?:\\Q \\E)|\\\\n|\\\\t|\\\\\\\\|\\\\'|\\\\\")*\"))|((?:\\b[A-Z_a-z][0-9A-Z_a-z]*\\b))|((?:.[\\x80-\\xbf]*))";
  static const reflex::Pattern PATTERN_INITIAL(REGEX_INITIAL);
  if (!has_matcher())
  {
    matcher(new Matcher(PATTERN_INITIAL, stdinit(), this));
  }
  while (true)
  {
        switch (matcher().scan())
        {
          case 0:
            if (matcher().at_end())
            {
#line 89 "lexer.ll"
{Token t(token_type::END_OF_FILE,0,lineno(),columno(),columno_end()); return t;}
            }
            else
            {
              out().put(matcher().input());
            }
            break;
          case 1: // rule lexer.ll:74: \/\/\N*\n :
#line 74 "lexer.ll"
{continue;}
            break;
          case 2: // rule lexer.ll:75: #\N*\n :
#line 75 "lexer.ll"
{continue;}
            break;
          case 3: // rule lexer.ll:76: (?s:"/*"(.|\n)*?"*/") :
#line 76 "lexer.ll"
{continue;}
            break;
          case 4: // rule lexer.ll:78: \n :
#line 78 "lexer.ll"
{continue;}

            break;
          case 5: // rule lexer.ll:80: [ \t\r] :
#line 80 "lexer.ll"
{continue;}
            break;
          case 6: // rule lexer.ll:81: {OPERATOR2} :
#line 81 "lexer.ll"
{Token t(token_type::OPERATOR,str(),lineno(),columno(),columno_end()); return t;}
            break;
          case 7: // rule lexer.ll:82: {OPERATOR1} :
#line 82 "lexer.ll"
{Token t(token_type::OPERATOR,str(),lineno(),columno(),columno_end()); return t;}
            break;
          case 8: // rule lexer.ll:83: {KEYWORD} :
#line 83 "lexer.ll"
{Token t(token_type::KEYWORD,str(),lineno(),columno(),columno_end()); return t;}
            break;
          case 9: // rule lexer.ll:84: {INT} :
#line 84 "lexer.ll"
{Token t(token_type::UINT,stoi(str()),lineno(),columno(),columno_end()); return t;}
            break;
          case 10: // rule lexer.ll:85: {HEX} :
#line 85 "lexer.ll"
{std::istringstream hex{str()}; int i = 0; hex >> std::hex >> i; Token t(token_type::UINT,i,lineno(),columno(),columno_end()); return t;}
            break;
          case 11: // rule lexer.ll:86: {CHAR} :
#line 86 "lexer.ll"
{std::string txt = str();Token t(token_type::CHAR,txt.substr(1,txt.size()-2),lineno(),columno(),columno_end()); return t;}
            break;
          case 12: // rule lexer.ll:87: {STRING} :
#line 87 "lexer.ll"
{std::string txt = str();Token t(token_type::STRING,txt.substr(1,txt.size()-2),lineno(),columno(),columno_end()); return t;}
            break;
          case 13: // rule lexer.ll:88: {IDENTIFIER} :
#line 88 "lexer.ll"
{Token t(token_type::IDENT,str(),lineno(),columno(),columno_end()); return t;}
            break;
          case 14: // rule lexer.ll:90: . :
#line 90 "lexer.ll"
{std::ostringstream msg; msg << "Lexing Error on "<< lineno() << ":"<< columno(); throw std::runtime_error(msg.str());}

            break;
        }
  }
}

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 3: user code                                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#line 93 "lexer.ll"

#ifdef SCANNER_MAIN
int main(int argc, char* argv[]){

    if (argc != 2){
        exit(2);
    }

    std::ifstream codefile (argv[1]);
    if (!codefile.is_open()){
        exit(2);
    }

    scanner s(codefile);
    while (true){
        try {
                Token token = s.lex();
                switch (token.token_t){
                    case token_type::END_OF_FILE:
                        exit(0);
                        break;
                    case token_type::IDENT:
                        std::cout << "IDENT(" << std::get<std::string>(token.value) << ") ";
                        break;
                    case token_type::CHAR:
                        std::cout << "\'" << std::get<std::string>(token.value) << "\' ";
                        break;
                    case token_type::STRING:
                        std::cout << "\"" << std::get<std::string>(token.value) << "\" ";
                        break;
                    case token_type::UINT:
                        std::cout << "int(" << std::get<int>(token.value) << ") ";
                        break;
                    case token_type::KEYWORD:
                    case token_type::OPERATOR:
                        std::cout << std::get<std::string>(token.value) << " ";
                        break;
                }
        }catch (std::runtime_error err) {
            std::cout << err.what() << std::endl;
            exit(1);
        }
    }
}
#endif
