// scanner.hpp generated by reflex 5.1.0 from lexer.ll

#ifndef REFLEX_SCANNER_HPP
#define REFLEX_SCANNER_HPP
#define IN_HEADER 1
#define REFLEX_VERSION "5.1.0"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  OPTIONS USED                                                              //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#define REFLEX_OPTION_header_file         "scanner.hpp"
#define REFLEX_OPTION_lex                 lex
#define REFLEX_OPTION_lexer               scanner
#define REFLEX_OPTION_outfile             "scanner.cpp"
#define REFLEX_OPTION_token_type          Token
#define REFLEX_OPTION_unicode             true

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %top user code                                                 //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#line 8 "lexer.ll"

#ifndef TOKEN_DEFINED
#define TOKEN_DEFINED
#include <iostream>
#include <fstream>
#include <sstream>
#include <variant>
#include <string>

class Token;

enum class token_type {
    IDENT,
    CHAR,
    UINT,
    STRING,
    OPERATOR,
    KEYWORD,
    END_OF_FILE,
};

typedef std::variant<std::string,int> token_value;

class Token {
    public:
        token_type token_t;
        token_value value;
        int line;
        int startc;
        int endc;

        Token() = delete;

        Token(token_type t, token_value&& v,int l, int sc){
            token_t = t;
            value = v;
            line = 0;
            startc = 0;
            endc =0;
        }

        Token(token_type t, token_value&& v,int l,int sc, int ec){
            token_t = t;
            value = v;
            line = l;
            startc = sc;
            endc = ec;
        }
};

#endif


////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  REGEX MATCHER                                                             //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/matcher.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  ABSTRACT LEXER CLASS                                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/abslexer.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  LEXER CLASS                                                               //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

class scanner : public reflex::AbstractLexer<reflex::Matcher> {
 public:
  typedef reflex::AbstractLexer<reflex::Matcher> AbstractBaseLexer;
  scanner(
      // a persistent source of input, empty by default
      const reflex::Input& input = reflex::Input(),
      // optional output stream, std::cout by default
      std::ostream& os = std::cout)
    :
      AbstractBaseLexer(input, os)
  {
  }
  static const int INITIAL = 0;
  // the lexer function defined by SECTION 2
  virtual Token lex(void);
  // lexer functions accepting new input to scan
  Token lex(const reflex::Input& input)
  {
    in(input);
    return lex();
  }
  Token lex(const reflex::Input& input, std::ostream *os)
  {
    in(input);
    if (os)
      out(*os);
    return lex();
  }
};

#endif
